/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;


import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType media.
 *
 * @since 2025-10-19
 */
@PrimaryKeys({"mediaID", "order"})
public final class media extends CloudDBZoneObject {
    private String mediaID;

    private Integer order;

    private String mediaType;

    private String mediaURI;

    @NotNull
    @DefaultValue(booleanValue = true)
    private Boolean forLog;

    public media() {
        super(media.class);
        this.forLog = true;
    }

    public void setMediaID(String mediaID) {
        this.mediaID = mediaID;
    }

    public String getMediaID() {
        return mediaID;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Integer getOrder() {
        return order;
    }

    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    public String getMediaType() {
        return mediaType;
    }

    public void setMediaURI(String mediaURI) {
        this.mediaURI = mediaURI;
    }

    public String getMediaURI() {
        return mediaURI;
    }

    public void setForLog(Boolean forLog) {
        this.forLog = forLog;
    }

    public Boolean getForLog() {
        return forLog;
    }

}
