name: project_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1

  # --- Core Service & Permissions ---
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  android_intent_plus: ^5.1.0
  sensors_plus: ^5.0.1
  # flutter_sound: ^9.2.13  # UNUSED - Commented out for faster builds
  record: ^6.1.2 # Audio recording with amplitude monitoring for dB detection
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  path_provider: ^2.0.0 # Often needed with flutter_sound
  geocoding: ^3.0.0 # Added for reverse geocoding
  speech_to_text: ^7.3.0 # Or the latest version
  google_generative_ai: ^0.4.0
  http: ^1.1.0
  image_picker: ^1.0.4
  video_thumbnail: ^0.5.3
  file_picker: ^8.1.4
  video_player: ^2.8.0
  audioplayers: ^5.2.1
  intl: ^0.18.0
  flutter_dotenv: ^5.1.0
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1


  #  Huawei/HMS
  # huawei_site: ^6.5.1+303  # UNUSED - Commented out for faster builds
  huawei_map:
    path: plugins/huawei_map
  huawei_location: 6.11.0+301
  # huawei_ml_text:  # UNUSED - Commented out for faster builds
  #   path: plugins/huawei_ml_text
  # huawei_ml_body:  # UNUSED - Commented out for faster builds
  #   path: plugins/huawei_ml_body
  # huawei_ml_image:  # UNUSED - Commented out for faster builds
  #   path: plugins/huawei_ml_image
  # huawei_ml_language:  # UNUSED - Commented out for faster builds
  #   path: plugins/huawei_ml_language
  huawei_account:
    path: plugins/huawei_account
  huawei_push:
    path: plugins/huawei_push
  # huawei_drive:  # UNUSED - Commented out for faster builds
  #     path: plugins/huawei_drive
  agconnect_core:
      path: plugins/agconnect_core
  agconnect_auth:
      path: plugins/agconnect_auth
  agconnect_cloudstorage:
      path: plugins/agconnect_cloudstorage
  # agconnect_cloudfunctions:  # UNUSED - Commented out for faster builds
  #     path: plugins/agconnect_cloudfunctions
  agconnect_clouddb:
      path: plugins/agconnect_clouddb
  # agconnect_crash:  # UNUSED - Commented out for faster builds
  #     path: plugins/agconnect_crash

  # --- Core Service ---
  # Manages the foreground service and background isolate
  flutter_background_service: ^5.0.0
  # --- Permissions ---
  # For requesting Audio, Location, Sensors, etc.
  permission_handler: ^11.3.1
  # --- IMU Sensors ---
  # Access Accelerometer, Gyroscope, etc.
  sensors_plus: ^5.0.1
  # --- Audio Recording ---
  # To capture audio for analysis and upload
  # We use this to create the audio file for DriveKit
  flutter_sound: ^9.2.13
  # --- Huawei HMS Kits ---
  agconnect_core: ^1.9.0+300
  agconnect_clouddb: ^1.9.0+300
  huawei_location: ^6.12.0+300 # Use latest compatible
  huawei_map: ^6.11.0+301
  huawei_ml_body: ^3.12.0+300 # For Sound Detect & ASR
  huawei_drive: ^5.0.0+308
  huawei_push: ^6.13.0+300

  # --- Utility ---
  # For generating unique IDs for 'uid' and 'mediaID'
  uuid: ^4.4.0
  # For local storage of the device's unique ID
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/mysafezone_logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/mysafezone_logo.png
    - assets/images/AI_lodge1.jpg
    - assets/images/AI_lodge2.jpg
    - assets/images/AI_lodge3.jpg
    - assets/images/AI_lodge4.jpg
  fonts:
  - family: Goldman
    fonts:
      - asset: assets/fonts/goldman/Goldman-Regular.ttf
      - asset: assets/fonts/goldman/Goldman-Bold.ttf
        weight: 700
