name: project_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Core Service & Permissions ---
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  sensors_plus: ^5.0.1
  flutter_sound: ^9.2.13
  record: ^6.1.2
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  path_provider: ^2.0.0 # Often needed with flutter_sound

  #  Huawei/HMS
  huawei_map:
    path: plugins/huawei_map
  huawei_location: 6.11.0+301
  huawei_ml_text:
    path: plugins/huawei_ml_text
  huawei_ml_body:
    path: plugins/huawei_ml_body
  huawei_ml_image:
    path: plugins/huawei_ml_image
  huawei_ml_language:
    path: plugins/huawei_ml_language
  huawei_account:
    path: plugins/huawei_account
  huawei_push:
    path: plugins/huawei_push
  huawei_drive:
      path: plugins/huawei_drive
  agconnect_core:
      path: plugins/agconnect_core
  agconnect_auth:
      path: plugins/agconnect_auth
  agconnect_cloudstorage:
      path: plugins/agconnect_cloudstorage
  agconnect_cloudfunctions:
      path: plugins/agconnect_cloudfunctions
  agconnect_clouddb:
      path: plugins/agconnect_clouddb
  agconnect_crash:
      path: plugins/agconnect_crash

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/mysafezone_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/mysafezone_logo.png
  fonts:
  - family: Goldman
    fonts:
      - asset: assets/fonts/goldman/Goldman-Regular.ttf
      - asset: assets/fonts/goldman/Goldman-Bold.ttf
        weight: 700