name: project_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  huawei_map:
    path: plugins/huawei_map
  huawei_location: 6.11.0+301
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mysafezone_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/mysafezone_logo.png
  fonts:
  - family: Goldman
    fonts:
      - asset: assets/fonts/goldman/Goldman-Regular.ttf
      - asset: assets/fonts/goldman/Goldman-Bold.ttf
        weight: 700