/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType IncidentLogs.
 *
 * @since 2025-10-24
 */
@PrimaryKeys({"iid", "timestamp"})
public final class IncidentLogs extends CloudDBZoneObject {
    private String iid;

    private String timestamp;

    @NotNull
    @DefaultValue(stringValue = "")
    private String sensorJsonData;

    private String aiDesc;

    public IncidentLogs() {
        super(IncidentLogs.class);
        this.sensorJsonData = "";
    }

    public void setIid(String iid) {
        this.iid = iid;
    }

    public String getIid() {
        return iid;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setSensorJsonData(String sensorJsonData) {
        this.sensorJsonData = sensorJsonData;
    }

    public String getSensorJsonData() {
        return sensorJsonData;
    }

    public void setAiDesc(String aiDesc) {
        this.aiDesc = aiDesc;
    }

    public String getAiDesc() {
        return aiDesc;
    }

}
