/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Users.
 *
 * @since 2025-10-24
 */
@PrimaryKeys({"uid"})
@Indexes({"uid:uid", "postcode:postcode"})
public final class Users extends CloudDBZoneObject {
    private String uid;

    private String district;

    private String postcode;

    private String state;

    private String username;

    private String phoneNo;

    private Boolean allowDiscoverable;

    private Boolean allowEmergencyAlert;

    private Double latitude;

    private Double longtitude;

    private String email;

    public Users() {
        super(Users.class);
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getDistrict() {
        return district;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getState() {
        return state;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return username;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    public String getPhoneNo() {
        return phoneNo;
    }

    public void setAllowDiscoverable(Boolean allowDiscoverable) {
        this.allowDiscoverable = allowDiscoverable;
    }

    public Boolean getAllowDiscoverable() {
        return allowDiscoverable;
    }

    public void setAllowEmergencyAlert(Boolean allowEmergencyAlert) {
        this.allowEmergencyAlert = allowEmergencyAlert;
    }

    public Boolean getAllowEmergencyAlert() {
        return allowEmergencyAlert;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLongtitude(Double longtitude) {
        this.longtitude = longtitude;
    }

    public Double getLongtitude() {
        return longtitude;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

}
