/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType incidents.
 *
 * @since 2025-10-22
 */
@PrimaryKeys({"iid", "uid"})
@Indexes({"uid:uid", "iid:iid"})
public final class incidents extends CloudDBZoneObject {
    private String iid;

    private String uid;

    private String latitude;

    private String longitude;

    private Date datetime;

    private String incidentType;

    private String desc;

    private String mediaID;

    private String status;

    private Boolean isAIGenerated;

    public incidents() {
        super(incidents.class);
    }

    public void setIid(String iid) {
        this.iid = iid;
    }

    public String getIid() {
        return iid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public Date getDatetime() {
        return datetime;
    }

    public void setIncidentType(String incidentType) {
        this.incidentType = incidentType;
    }

    public String getIncidentType() {
        return incidentType;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getDesc() {
        return desc;
    }

    public void setMediaID(String mediaID) {
        this.mediaID = mediaID;
    }

    public String getMediaID() {
        return mediaID;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setIsAIGenerated(Boolean isAIGenerated) {
        this.isAIGenerated = isAIGenerated;
    }

    public Boolean getIsAIGenerated() {
        return isAIGenerated;
    }

}
